hook.Add("PopulateToolMenu", "CrosshairDot_Settings", function()
	spawnmenu.AddToolMenuOption("Utilities", "User", "CrosshairDot", "Прицел", "", "", function(panel)
		panel:ClearControls()
    panel:CheckBox("Enabled", "crosshairdot_enabled")
    panel:CheckBox("Outline", "crosshairdot_enabled_outline")
    panel:CheckBox("Thirdperson", "crosshairdot_thirdperson")
		panel:NumSlider("Dot Size:", "crosshairdot_size", 0, 50)
		panel:NumSlider("Outline Size:", "crosshairdot_outline_size", 0, 20)
    panel:Button("Reset to Default", "crosshairdot_reset")

    local DynamicList = vgui.Create("DForm")
    DynamicList:SetLabel("Dynamic Settings")
    DynamicList:DockMargin(-10, 10, -10, 0)
    DynamicList:DockPadding(0,0,0,10)
    DynamicList:SetExpanded(true)
    
    DynamicList:CheckBox("Dynamic 3D Dot", "crosshairdot_dynamic3d")
    DynamicList:CheckBox("Dynamic Angles", "crosshairdot_enabled_dynamic_angles")
    DynamicList:CheckBox("Dynamic Distance", "crosshairdot_enabled_dynamic_distance")
    DynamicList:CheckBox("Dynamic Shake", "crosshairdot_enabled_dynamic_shake")
    
		DynamicList:NumSlider("Smooth Speed:", "crosshairdot_smooth_speed", 0.1, 1)
		DynamicList:NumSlider("Dynamic Angles Scale:", "crosshairdot_dynamic_angles_scale", 0, 1)
		DynamicList:NumSlider("Dynamic Shake Scale:", "crosshairdot_dynamic_shake_scale", 0, 1)
    
    DynamicList:CheckBox("Dynamic Color", "crosshairdot_enabled_dynamic_color")
    
    panel:AddItem(DynamicList)

    local ColorList = vgui.Create("DForm")
    ColorList:SetLabel("Color Settings")
    ColorList:DockMargin(-10, -5, -10, 0)
    ColorList:DockPadding(0,0,0,10)
    ColorList:SetExpanded(false)
    
    local DotColorLabel = vgui.Create("DLabel")
    DotColorLabel:SetText("Dot Color:")
    DotColorLabel:SetColor(Color(0,0,0, 255))
    ColorList:AddItem(DotColorLabel)
    
    local DotColor = vgui.Create("DColorMixer")
    DotColor:SetConVarR("crosshairdot_dotcolor_r")
    DotColor:SetConVarG("crosshairdot_dotcolor_g")
    DotColor:SetConVarB("crosshairdot_dotcolor_b")
    DotColor:SetConVarA("crosshairdot_dotcolor_a")
    ColorList:AddItem(DotColor)
    
    local OutlineColorLabel = vgui.Create("DLabel")
    OutlineColorLabel:SetText("Outline Color:")
    OutlineColorLabel:SetColor(Color(0,0,0, 255))
    ColorList:AddItem(OutlineColorLabel)
    
    local OutlineColor = vgui.Create("DColorMixer")
    OutlineColor:SetConVarR("crosshairdot_outlinecolor_r")
    OutlineColor:SetConVarG("crosshairdot_outlinecolor_g")
    OutlineColor:SetConVarB("crosshairdot_outlinecolor_b")
    OutlineColor:SetConVarA("crosshairdot_outlinecolor_a")
    ColorList:AddItem(OutlineColor)
    
    local DynamicColorLabel = vgui.Create("DLabel")
    DynamicColorLabel:SetText("Dynamic Color:")
    DynamicColorLabel:SetColor(Color(0,0,0, 255))
    ColorList:AddItem(DynamicColorLabel)
    
    local DynamicColor = vgui.Create("DColorMixer")
    DynamicColor:SetConVarR("crosshairdot_dynamiccolor_r")
    DynamicColor:SetConVarG("crosshairdot_dynamiccolor_g")
    DynamicColor:SetConVarB("crosshairdot_dynamiccolor_b")
    DynamicColor:SetConVarA("crosshairdot_dynamiccolor_a")
    ColorList:AddItem(DynamicColor)
    
    panel:AddItem(ColorList)
	end)
end)